# Generated by Django 6.0.3 on 2026-05-01 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='utilsateur',
            new_name='utilisateur',
        ),
    ]
