from .base import *
from .utilisateurs import *
from .etablissements import *
from .pedagogie import *
from .visioconference import *
from .examens import *
from .intelligence_artificielle import *
from .boutique import *
from .communications import *