# Generated by Django 6.0.3 on 2026-04-04 23:45

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Chapitre',
                'verbose_name_plural': 'Chapitres',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('adresse', models.CharField(max_length=255)),
                ('telephone', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(regex='^\\+?[0-9]{8,15}$')])),
                ('email', models.EmailField(max_length=254)),
                ('code_etablissement', models.CharField(max_length=20, unique=True)),
            ],
            options={
                'verbose_name': 'Etablissement',
                'verbose_name_plural': 'Etablissements',
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Matière',
                'verbose_name_plural': 'Matières',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='NiveauScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(choices=[('Maternelle', 'Maternelle'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6ème', '6ème'), ('5ème', '5ème'), ('4ème', '4ème'), ('3ème', '3ème'), ('2nde', '2nde'), ('1ère', '1ère'), ('Terminale', 'Terminale')], max_length=20, unique=True)),
                ('ordre', models.IntegerField(unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Niveau Scolaire',
                'verbose_name_plural': 'Niveaux Scolaires',
                'ordering': ['ordre'],
            },
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('date_suppression', models.DateTimeField(blank=True, null=True)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('langue_preferee', models.CharField(choices=[('MG', 'Malagasy'), ('FR', 'Français'), ('EN', 'Anglais')], default='MG', max_length=2)),
                ('options_accessibilite', models.JSONField(blank=True, default=dict)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('type_utilisateur', models.CharField(choices=[('ETUDIANT', 'Étudiant'), ('ENSEIGNANT', 'Enseignant'), ('ADMINISTRATEUR', 'Administrateur')], default='ETUDIANT', max_length=25)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
                'ordering': ['-date_creation'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminPlateforme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('niveau_acces', models.CharField(default='super_admin', max_length=50)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Administrateur',
                'verbose_name_plural': 'Administrateurs',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialite', models.CharField(blank=True, max_length=100)),
                ('date_embauche', models.DateField()),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
        ),
        migrations.CreateModel(
            name='AdminEtablissement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fonction', models.CharField(max_length=100)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='core.etablissement')),
            ],
            options={
                'verbose_name': "Administrateur  d'Etablissement",
                'verbose_name_plural': "Adminstrateurs d' Etablissement ",
            },
        ),
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('contenu', models.TextField()),
                ('date_expiration', models.DateTimeField(blank=True, null=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('public_ciblie', models.CharField(choices=[('TOUS', 'Tous'), ('ETUDIANTS', 'Etudiants'), ('ENSEIGNANTS', 'Enseignants'), ('ETABLISSEMENT', 'Etablissements')], default='TOUS', max_length=20)),
                ('etablissement_cible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.etablissement')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_global', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='etudiant_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('montant_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut_paiement', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('PAYEE', 'Payée'), ('LIVREE', 'Livrée'), ('ANNULEE', 'Annulée')], default='EN_ATTENTE', max_length=20)),
                ('reference_paiement', models.CharField(blank=True, max_length=100, unique=True)),
                ('date_paiement', models.DateTimeField(blank=True, null=True)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commandes', to='core.etudiant')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commades',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Examen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('duree_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('est_publie', models.BooleanField(default=False)),
                ('coefficient', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0)])),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='core.enseignant')),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='core.matiere')),
                ('niveau', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examens', to='core.niveauscolaire')),
            ],
            options={
                'verbose_name': 'Examen',
                'verbose_name_plural': 'Examens',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='CopieExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_soumission', models.DateTimeField(blank=True, null=True)),
                ('note_obtenue', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)])),
                ('est_termine', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies_examens', to='core.etudiant')),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='core.examen')),
            ],
            options={
                'verbose_name': "Copie d'examen",
                'verbose_name_plural': "Copies d'examen",
                'unique_together': {('examen', 'etudiant')},
            },
        ),
        migrations.CreateModel(
            name='Lecon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField()),
                ('contenue_texte', models.TextField(blank=True)),
                ('duree_estimee', models.PositiveIntegerField(help_text='Durée estimée en minutes')),
                ('objectifs', models.TextField(blank=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecons', to='core.chapitre')),
            ],
            options={
                'verbose_name': 'Leçon',
                'verbose_name_plural': 'Leçons',
                'ordering': ['order'],
                'unique_together': {('chapitre', 'order')},
            },
        ),
        migrations.CreateModel(
            name='FichierMultimedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_fichier', models.CharField(choices=[('VIDEO', 'Vidéo'), ('AUDIO', 'Audio'), ('PDF', 'Document PDF')], max_length=20)),
                ('titre', models.CharField(max_length=200)),
                ('url_fichier', models.URLField()),
                ('taille_no', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('format', models.CharField(max_length=10)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fichiers', to='core.lecon')),
            ],
            options={
                'verbose_name': 'Fichier Multimédia',
                'verbose_name_plural': 'Fichiers Multimédia',
            },
        ),
        migrations.CreateModel(
            name='LogSurveillace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evenement', models.CharField(max_length=200)),
                ('details', models.JSONField(default=dict)),
                ('date_evenement', models.DateTimeField(auto_now_add=True)),
                ('copie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.copieexamen')),
            ],
            options={
                'verbose_name': 'Log de surveillance ',
                'verbose_name_plural': 'Logs de surveillance ',
                'ordering': ['-date_evenement'],
            },
        ),
        migrations.AddField(
            model_name='chapitre',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='core.matiere'),
        ),
        migrations.AddField(
            model_name='matiere',
            name='niveaux',
            field=models.ManyToManyField(related_name='matieres', to='core.niveauscolaire'),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapitres', to='core.niveauscolaire'),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('est_lue', models.BooleanField(default=False)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('url_lien', models.URLField(blank=True)),
                ('utilsateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Panier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_derniere_modif', models.DateTimeField(auto_now=True)),
                ('etudiant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='panier', to='core.etudiant')),
            ],
            options={
                'verbose_name': 'Panier',
                'verbose_name_plural': 'Paniers',
            },
        ),
        migrations.CreateModel(
            name='QuestionExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField()),
                ('type_question', models.CharField(choices=[('QCM', 'Question à choix multiples '), ('TEXTE', 'Réponse texte'), ('NUMERIQUE', 'Réponse numérique'), ('VRAI_FAUX', 'Vrai/Faux')], max_length=10)),
                ('points', models.FloatField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ordre', models.PositiveIntegerField()),
                ('options', models.JSONField(blank=True, default=list)),
                ('reponse_correcte', models.TextField()),
                ('examen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.examen')),
            ],
            options={
                'verbose_name': 'Question Examen',
                'verbose_name_plural': "Questions d'examen",
                'ordering': ['ordre'],
                'unique_together': {('examen', 'ordre')},
            },
        ),
        migrations.CreateModel(
            name='Recommandation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('score_pertinence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('explication', models.TextField()),
                ('est_consultee', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandations', to='core.etudiant')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommandation', to='core.lecon')),
            ],
            options={
                'verbose_name': 'Recommandation',
                'verbose_name_plural': 'Recommandations',
                'ordering': ['-score_pertinence', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RequestIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('request', models.TextField()),
                ('reponse', models.TextField()),
                ('type_requete', models.CharField(choices=[('NAVIGATION', 'Navigation'), ('RECOMMANDATION', 'Recommandation'), ('AIDE', 'Aide')], max_length=20)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requetes_ia', to='core.etudiant')),
            ],
            options={
                'verbose_name': 'Requete IA',
                'verbose_name_plural': 'Requetes IA ',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='RessourceBoutique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('type_contenu', models.CharField(choices=[('LIVRE', 'Livre numérique'), ('EXERCICES', 'Exercices'), ('COURS', 'Cours premium'), ('VIDEO', 'Vidéo')], max_length=10)),
                ('est_disponible', models.BooleanField(default=True)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('fichier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fichiermultimedia')),
                ('matiere', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.matiere')),
                ('niveau', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.niveauscolaire')),
            ],
            options={
                'verbose_name': 'Ressources boutique ',
                'verbose_name_plural': 'Ressorces boutique',
            },
        ),
        migrations.CreateModel(
            name='SessionVisio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('titre', models.CharField(max_length=200)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('url_visio', models.URLField()),
                ('est_active', models.BooleanField(default=False)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_visio', to='core.enseignant')),
                ('lecon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_visio', to='core.lecon')),
            ],
            options={
                'verbose_name': 'Session de visioconférence',
                'verbose_name_plural': 'Sessions de visioconférence',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chapitre',
            unique_together={('matiere', 'niveau', 'order')},
        ),
        migrations.CreateModel(
            name='ReponseExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reponse_etudiant', models.TextField()),
                ('est_correct', models.BooleanField(default=False)),
                ('points_obtenus', models.FloatField(default=0)),
                ('copie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reponses', to='core.copieexamen')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.questionexamen')),
            ],
            options={
                'unique_together': {('copie', 'question')},
            },
        ),
        migrations.CreateModel(
            name='PanierItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('panier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.panier')),
                ('ressources', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ressourceboutique')),
            ],
            options={
                'verbose_name': 'Element du panier ',
                'verbose_name_plural': 'Elements du panier ',
                'unique_together': {('panier', 'ressources')},
            },
        ),
        migrations.CreateModel(
            name='ParticipationVisio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joindre', models.DateTimeField(auto_now_add=True)),
                ('date_quitter', models.DateTimeField(blank=True, null=True)),
                ('duree_participation', models.PositiveIntegerField(default=0)),
                ('evenements_inactive', models.JSONField(default=list)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sessionvisio')),
            ],
            options={
                'verbose_name': 'Participation visioconférence',
                'verbose_name_plural': 'Participations visioconférence',
                'unique_together': {('etudiant', 'session')},
            },
        ),
    ]
