# Generated by Django 6.0.5 on 2026-05-27 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adminetablissement',
            options={'ordering': ['-id'], 'verbose_name': "Administrateur  d'Etablissement", 'verbose_name_plural': "Adminstrateurs d' Etablissement "},
        ),
        migrations.AlterModelOptions(
            name='adminplateforme',
            options={'ordering': ['-id'], 'verbose_name': 'Administrateur', 'verbose_name_plural': 'Administrateurs'},
        ),
        migrations.AlterModelOptions(
            name='copieexamen',
            options={'ordering': ['-id'], 'verbose_name': "Copie d'examen", 'verbose_name_plural': "Copies d'examen"},
        ),
        migrations.AlterModelOptions(
            name='enseignant',
            options={'ordering': ['-id'], 'verbose_name': 'Enseignant', 'verbose_name_plural': 'Enseignants'},
        ),
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['-id'], 'verbose_name': 'Etablissement', 'verbose_name_plural': 'Etablissements'},
        ),
        migrations.AlterModelOptions(
            name='etudiant',
            options={'ordering': ['-id'], 'verbose_name': 'Etudiant', 'verbose_name_plural': 'Etudiants'},
        ),
        migrations.AlterModelOptions(
            name='fichiermultimedia',
            options={'ordering': ['-id'], 'verbose_name': 'Fichier Multimédia', 'verbose_name_plural': 'Fichiers Multimédia'},
        ),
        migrations.AlterModelOptions(
            name='panier',
            options={'ordering': ['-id'], 'verbose_name': 'Panier', 'verbose_name_plural': 'Paniers'},
        ),
        migrations.AlterModelOptions(
            name='panieritem',
            options={'ordering': ['-id'], 'verbose_name': 'Element du panier ', 'verbose_name_plural': 'Elements du panier '},
        ),
        migrations.AlterModelOptions(
            name='participationvisio',
            options={'ordering': ['-id'], 'verbose_name': 'Participation visioconférence', 'verbose_name_plural': 'Participations visioconférence'},
        ),
        migrations.AlterModelOptions(
            name='progressionchapitre',
            options={'ordering': ['-id'], 'verbose_name': 'Progression Chapitre', 'verbose_name_plural': 'Progressions Chapitres'},
        ),
        migrations.AlterModelOptions(
            name='reponseexamen',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='ressourceboutique',
            options={'ordering': ['-id'], 'verbose_name': 'Ressources boutique ', 'verbose_name_plural': 'Ressorces boutique'},
        ),
        migrations.AddField(
            model_name='examen',
            name='lecture_automatique',
            field=models.BooleanField(default=False, help_text='Lecture automatique des sujets'),
        ),
        migrations.AddField(
            model_name='examen',
            name='type_examen',
            field=models.CharField(choices=[('QCM', 'QCM'), ('TEXTE', 'Question/Réponse'), ('REDACTION', 'Rédaction'), ('MIXTE', 'Mixte')], default='MIXTE', max_length=20),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='criteres_correction',
            field=models.JSONField(blank=True, default=dict, help_text='Critères de correction (orthographe, nb mots, idées)'),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='mot_max',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre maximum de mots pour les questions de rédaction', null=True),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='mot_min',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre minimum de mots pour les questions de rédaction', null=True),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='obligatoire',
            field=models.BooleanField(default=True, help_text='Question obligatoire'),
        ),
        migrations.AddField(
            model_name='reponseexamen',
            name='correction_commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='reponseexamen',
            name='fautes_orthographe',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='reponseexamen',
            name='nb_mots',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='questionexamen',
            name='type_question',
            field=models.CharField(choices=[('QCM', 'Question à choix multiples '), ('TEXTE', 'Réponse texte'), ('NUMERIQUE', 'Réponse numérique'), ('VRAI_FAUX', 'Vrai/Faux'), ('REDACTION', 'Rédaction')], max_length=10),
        ),
        migrations.CreateModel(
            name='QuestionVisio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('est_answered', models.BooleanField(default=False)),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.etudiant')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.sessionvisio')),
            ],
            options={
                'verbose_name': 'Question visioconférence',
                'verbose_name_plural': 'Questions visioconférence',
                'ordering': ['date_creation'],
            },
        ),
    ]
