# Generated by Django 6.0.5 on 2026-05-27 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_adminetablissement_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_creation'], 'verbose_name': 'Commande', 'verbose_name_plural': 'Commandes'},
        ),
        migrations.AlterModelOptions(
            name='ressourceboutique',
            options={'ordering': ['-id'], 'verbose_name': 'Ressource boutique', 'verbose_name_plural': 'Ressources boutique'},
        ),
    ]
