# Generated by Django 6.0.4 on 2026-05-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_utilsateur_notification_utilisateur'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='contenu_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='contenu_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='contenu_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='titre_mg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='adminetablissement',
            name='fonction_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminetablissement',
            name='fonction_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='adminetablissement',
            name='fonction_mg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='description_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='chapitre',
            name='titre_mg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='specialite_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='specialite_fr',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='specialite_mg',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='adresse_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='adresse_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='adresse_mg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='nom_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='nom_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='etablissement',
            name='nom_mg',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='examen',
            name='titre_mg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fichiermultimedia',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fichiermultimedia',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fichiermultimedia',
            name='titre_mg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='contenue_texte_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='contenue_texte_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='contenue_texte_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='objectifs_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='objectifs_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='objectifs_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='lecon',
            name='titre_mg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='description_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='nom_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='nom_fr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='matiere',
            name='nom_mg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='niveauscolaire',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='niveauscolaire',
            name='description_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='niveauscolaire',
            name='description_mg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='niveauscolaire',
            name='nom_en',
            field=models.CharField(choices=[('Maternelle', 'Maternelle'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6ème', '6ème'), ('5ème', '5ème'), ('4ème', '4ème'), ('3ème', '3ème'), ('2nde', '2nde'), ('1ère', '1ère'), ('Terminale', 'Terminale')], max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='niveauscolaire',
            name='nom_fr',
            field=models.CharField(choices=[('Maternelle', 'Maternelle'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6ème', '6ème'), ('5ème', '5ème'), ('4ème', '4ème'), ('3ème', '3ème'), ('2nde', '2nde'), ('1ère', '1ère'), ('Terminale', 'Terminale')], max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='niveauscolaire',
            name='nom_mg',
            field=models.CharField(choices=[('Maternelle', 'Maternelle'), ('CP', 'CP'), ('CE1', 'CE1'), ('CE2', 'CE2'), ('CM1', 'CM1'), ('CM2', 'CM2'), ('6ème', '6ème'), ('5ème', '5ème'), ('4ème', '4ème'), ('3ème', '3ème'), ('2nde', '2nde'), ('1ère', '1ère'), ('Terminale', 'Terminale')], max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre_mg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='reponse_correcte_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='reponse_correcte_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='reponse_correcte_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='texte_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='texte_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='questionexamen',
            name='texte_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ressourceboutique',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ressourceboutique',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ressourceboutique',
            name='description_mg',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ressourceboutique',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ressourceboutique',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ressourceboutique',
            name='titre_mg',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sessionvisio',
            name='titre_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sessionvisio',
            name='titre_fr',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sessionvisio',
            name='titre_mg',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
