# Generated by Django 6.0.4 on 2026-05-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_actualite_contenu_en_actualite_contenu_fr_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='numero_etudiant',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
