# Generated by Django 6.0.4 on 2026-05-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_commande_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='etablissement',
            options={'ordering': ['type', 'nom'], 'verbose_name': 'Etablissement', 'verbose_name_plural': 'Etablissements'},
        ),
        migrations.AddField(
            model_name='etablissement',
            name='type',
            field=models.CharField(choices=[('LYCEE', 'Lycée'), ('CEG', 'CEG'), ('EPP', 'EPP'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10),
        ),
    ]
