# Generated by Django 6.0.4 on 2026-05-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_etudiant_numero_etudiant'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichiermultimedia',
            name='est_telechargeable',
            field=models.BooleanField(default=True, help_text='Si faux, le fichier est uniquement lisible sur la plateforme.'),
        ),
    ]
