# Generated by Django 6.0.3 on 2026-05-27 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_classe_etudiant_classe'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='niveau',
            field=models.ForeignKey(blank=True, help_text='Niveau unique que cet enseignant peut enseigner', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enseignants', to='core.niveauscolaire'),
        ),
    ]
