# Generated by Django 6.0.4 on 2026-05-13 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_fichiermultimedia_est_telechargeable'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='core.niveauscolaire'),
        ),
    ]
