# Generated by Django 6.0.4 on 2026-05-13 05:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_etudiant_niveau'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressionChapitre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temps_passe_secondes', models.PositiveIntegerField(default=0)),
                ('est_valide', models.BooleanField(default=False)),
                ('date_derniere_session', models.DateTimeField(auto_now=True)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='core.chapitre')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='core.etudiant')),
            ],
            options={
                'verbose_name': 'Progression Chapitre',
                'verbose_name_plural': 'Progressions Chapitres',
                'unique_together': {('etudiant', 'chapitre')},
            },
        ),
    ]
