# Generated by Django 6.0.4 on 2026-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_progressionchapitre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('logo', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True)),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Partenaire',
                'verbose_name_plural': 'Partenaires',
                'ordering': ['ordre', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Renovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.CharField(max_length=4)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('ordre', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Rénovation',
                'verbose_name_plural': 'Rénovations',
                'ordering': ['-annee', 'ordre'],
            },
        ),
    ]
