# Generated by Django 6.0.5 on 2026-05-29 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_chapitre_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL vidéo externe (YouTube, Vimeo, etc.)'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='contenue_texte',
            field=models.TextField(blank=True, help_text='Contenu en HTML (rich text)'),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='contenue_texte_en',
            field=models.TextField(blank=True, help_text='Contenu en HTML (rich text)', null=True),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='contenue_texte_fr',
            field=models.TextField(blank=True, help_text='Contenu en HTML (rich text)', null=True),
        ),
        migrations.AlterField(
            model_name='lecon',
            name='contenue_texte_mg',
            field=models.TextField(blank=True, help_text='Contenu en HTML (rich text)', null=True),
        ),
    ]
