# Generated by Django 6.0.4 on 2026-05-13 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_partenaire_renovation'),
    ]

    operations = [
        migrations.AddField(
            model_name='actualite',
            name='auteur',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites_publiees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actualite',
            name='categorie',
            field=models.CharField(choices=[('Examens', 'Examens'), ('Cours', 'Cours'), ('Événements', 'Événements'), ('Annonces', 'Annonces'), ('Sport', 'Sport'), ('Culture', 'Culture')], default='Annonces', max_length=30),
        ),
        migrations.AddField(
            model_name='actualite',
            name='est_important',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='actualite',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='actualites/'),
        ),
        migrations.AddField(
            model_name='actualite',
            name='lien_externe',
            field=models.URLField(blank=True, help_text='Lien vers une page externe', null=True),
        ),
        migrations.AddField(
            model_name='actualite',
            name='lien_label',
            field=models.CharField(blank=True, help_text='Texte du lien externe', max_length=100),
        ),
        migrations.AddField(
            model_name='actualite',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lien YouTube ou autre vidéo externe', null=True),
        ),
        migrations.AlterField(
            model_name='actualite',
            name='etablissement_cible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actualites', to='core.etablissement'),
        ),
    ]
