# Generated by Django 6.0.4 on 2026-05-13 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_actualite_rich_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEtude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('derniere_activite', models.DateTimeField(auto_now=True)),
                ('temps_cumule_secondes', models.PositiveIntegerField(default=0)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('PAUSE', 'En pause'), ('TERMINE', 'Terminé'), ('ABANDONNE', 'Abandonné')], default='EN_COURS', max_length=20)),
                ('chapitre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_etude', to='core.chapitre')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_etude', to='core.etudiant')),
            ],
            options={
                'verbose_name': "Session d'Étude",
                'verbose_name_plural': "Sessions d'Étude",
                'ordering': ['-derniere_activite'],
            },
        ),
    ]
