# Generated by Django 6.0.4 on 2026-05-13 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_sessionetude'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignants', to='core.etablissement'),
        ),
        migrations.AddField(
            model_name='etudiant',
            name='etablissement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='etudiants', to='core.etablissement'),
        ),
    ]
