# Generated by Django 6.0.5 on 2026-05-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_lecon_createur'),
    ]

    operations = [
        migrations.AddField(
            model_name='copieexamen',
            name='date_validation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='copieexamen',
            name='note_validee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='questionexamen',
            name='reponse_correcte',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='questionexamen',
            name='reponse_correcte_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='questionexamen',
            name='reponse_correcte_fr',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='questionexamen',
            name='reponse_correcte_mg',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
