# Generated by Django 6.0.5 on 2026-05-30 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_copieexamen_date_validation_copieexamen_note_validee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examen',
            name='session',
            field=models.CharField(choices=[('CC', 'Contrôle Continue'), ('EF', 'Examen Final')], default='EF', max_length=2),
        ),
    ]
