# Generated by Django 6.0.5 on 2026-06-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_utilsateur_notification_utilisateur'),
        ('core', '0012_examen_session'),
    ]

    operations = [
    ]
